#! /bin/bash

####
## BEGIN: Load common functions
etc/common.sh
## END: Load common functions
####

ARSENIC_OPT_PATH=$(dirname $ARSENIC_PATH)
OP_NAME=$(basename $(pwd))

ls -d $ARSENIC_OPT_PATH/*/scripts/as-init-op.sh 2>/dev/null | while read hook; do
  _ "running $hook"
  bash "$hook"
done

_ "Hooks completed"
