#! /bin/bash

####
## BEGIN: Load common functions
etc/common.sh
## END: Load common functions
####

FR_THREADS=100

if [ ! -z "$1" ]; then
  FR_THREADS="$1"
fi

set -uo pipefail

RECON_FILE="recon/ips/resolv-ips.txt"
if [ ! -f "$RECON_FILE" ] ; then
  mkdir -p "$(dirname $RECON_FILE)"

  _ 'Resolving IP Addresses'
  fast-resolv -c $FR_THREADS -d scope-ips-generated-public*.txt | tee "$RECON_FILE"
  cat "$RECON_FILE" | sort > sorted
  mv sorted "$RECON_FILE"
fi

set +o pipefail
cat "$RECON_FILE" \
| grep "domain name pointer" \
| awk '{print $NF}' \
| removeInvalidDomains \
| arsenic scope prune \
| tee scope-domains-generated-resolv-ips.txt
