#! /bin/bash

####
## BEGIN: Load common functions
etc/common.sh
## END: Load common functions
####

# Don't run any quick nmap scans through searchsploit
export COLUMNS=140
find . -name 'nmap-punched*.xml' -and -not -name '*quick*' | while read file; do
  echo '[!] checking '"$file"
  searchsploit --colour --nmap "$file" 2>/dev/null \
  | tee "$file.searchsploit.txt"
done
